version: '3.8'

x-server-basic: &server-basic
  build:
    context: ./
    dockerfile: ./server/Dockerfile
  volumes:
    - ./server:/server
  environment:
    DEBUG: 'True'
    DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres'
    BROKER_URL: 'amqp://user:password@rabbitmq:5672/my_vhost'
    REDIS_URL: 'redis://redis:6379/'

services:
  server:
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done;
                      gunicorn config.wsgi -c /server/config/gunicorn.py"
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    <<: *server-basic

  db:
    image: postgres:12.4-alpine
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

  redis:
    image: redis:6.0.7-alpine
