# Generated by Django 3.2.2 on 2021-05-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Number of views')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='adverts.category', verbose_name='Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='adverts.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'advert',
                'verbose_name_plural': 'adverts',
            },
        ),
    ]
